DROP TABLE IF EXISTS `bz_serviceinvoice`;
CREATE TABLE `bz_serviceinvoice` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `batch` int(11) DEFAULT NULL COMMENT '批次（业务数据id）',
  `dealer_no` varchar(50) DEFAULT NULL COMMENT '经销商 GSSN 号',
  `company_no` varchar(50) DEFAULT NULL COMMENT '记账公司 GSSN 号',
  `invoice_print_type` varchar(50) DEFAULT NULL COMMENT '账单类型:I-打印账单 C-退款单',
  `biz_type` varchar(50) DEFAULT NULL COMMENT '业务类型 W-工单',
  `invoice_no` varchar(50) DEFAULT NULL COMMENT '账单编号/退款编号',
  `doc_date` varchar(50) DEFAULT NULL COMMENT '账单/退款单日期',
  `customer_name` varchar(50) DEFAULT NULL COMMENT ' 客户名称',
  `company_name` varchar(50) DEFAULT NULL COMMENT '公司名称',
  `brand` varchar(50) DEFAULT NULL COMMENT '品牌',
  `model` varchar(50) DEFAULT NULL COMMENT '车型',
  `type` varchar(50) DEFAULT NULL COMMENT '乘用车--PC/商务车--CV',
  `registration_no` varchar(50) DEFAULT NULL COMMENT '车牌号',
  `fin` varchar(50) DEFAULT NULL COMMENT 'fin',
  `order_number` varchar(50) DEFAULT NULL COMMENT ' RWO 工单号码',
  `line_number` varchar(50) DEFAULT NULL COMMENT '项目行编号',
  `department_code` varchar(50) DEFAULT NULL COMMENT ' 部门代码',
  `parts_no` varchar(50) DEFAULT NULL COMMENT '零件编号',
  `description` varchar(200) DEFAULT NULL COMMENT '说明',
  `parts_analysis_code` varchar(50) DEFAULT NULL COMMENT 'Parts分析代码',
  `quantity` varchar(50) DEFAULT NULL COMMENT ' 数量',
  `parts_unit_cost` decimal(14,2) DEFAULT NULL COMMENT '配件单位成本',
  `part_genuine_flag` varchar(50) DEFAULT NULL COMMENT '原厂标记',
  `sales_type` varchar(50) DEFAULT NULL COMMENT '销售类型',
  `customer_type_no` varchar(50) DEFAULT NULL COMMENT '客户类型编号',
  `customer_type_no_description` varchar(50) DEFAULT NULL COMMENT '客户类型编号描述',
  `unit_net_price` decimal(14,2) DEFAULT NULL COMMENT '销售单价',
  `total_price` decimal(14,2) DEFAULT NULL COMMENT '销售总价',
  `discount_rate` decimal(14,2) DEFAULT NULL COMMENT '折扣百分比',
  `discount_amount` decimal(14,2) DEFAULT NULL COMMENT '折扣金额',
  `contribution` decimal(14,2) DEFAULT NULL COMMENT ' 分担比例',
  `contribution_amount` decimal(14,2) DEFAULT NULL COMMENT '供应商编号描述',
  `net_price` decimal(14,2) DEFAULT NULL COMMENT '净价',
  `package_mark` varchar(50) DEFAULT NULL COMMENT '套餐标志',
  `package_code` varchar(50) DEFAULT NULL COMMENT '套餐代码',
  `package_sequence` varchar(50) DEFAULT NULL COMMENT '套餐内序号',
  `vat_rate` decimal(14,2) DEFAULT NULL COMMENT '增值税税率',
  `vat_amount` decimal(14,2) DEFAULT NULL COMMENT '增值税税额',
  `labor_code` varchar(50) DEFAULT NULL COMMENT '工时代码',
  `labor_rate_code` varchar(50) DEFAULT NULL COMMENT '工时率代码 S-外加工',
  `standard_hour` varchar(50) DEFAULT NULL COMMENT '标准时间',
  `labor_retail_rate` decimal(14,2) DEFAULT NULL COMMENT '零售工时率',
  `supplier_no` varchar(50) DEFAULT NULL COMMENT '供应商编号',
  `supplier_no_description` varchar(50) DEFAULT NULL COMMENT '供应商编号描述',
  `sublet_estimate_cost` varchar(50) DEFAULT NULL COMMENT ' sublet 预估成 本',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='所有售后结账、退账的相关数据'